site_name: bytesizebio
site_description: Short and simple bioinformatics tutorials
site_author: A. Sina Booeshaghi
copyright: "Copyright &copy; 2020 - 2020 A. Sina Booeshaghi"
repo_url: https://github.com/sbooeshaghi/bytesizebio
repo_name: sbooeshaghi/bytesizebio

theme:
  name: material
  palette:
  - scheme: default
    primary: teal
    accent: amber
  features:
  - search.suggest
  - search.highlight
  language: en

google_analytics: ["G-188DM447D7", "bytesize.bio"]

markdown_extensions:
- toc:
    permalink: true
- admonition
- codehilite
- extra
- pymdownx.highlight:
    linenums: true
    linenums_style: pymdownx.inline
- pymdownx.superfences

extra:
  social:
    - type: "github"
      icon: fontawesome/brands/github
      link: "https://github.com/sbooeshaghi"
    - type: "twitter"
      icon: fontawesome/brands/twitter
      link: "https://twitter.com/sinabooeshaghi"

extra_css:
- css/custom.css


nav:
- Home: index.md
- Tutorials:
  - Interacting with FASTQ files: tutorials/terminal_interacting_with_fastq_files.md
